---
image: registry.dev-sandbox.fpcomplete.com/ops/default-build-image@sha256:ec289ae8a83e25afd594b64fb5ca098eeedbb7a7b0983d5396b645841164996b

stages:
  - lint
  - build

yamllint:
  stage: lint
  script:
    - ys=$(find -path */.terraform/*
                   -o -path ./.gitlab-ci.yml
                   -prune
                   -o -iname '*.yaml'
                   -o -iname '*.yml'
                   -print)
    - 'if [ ! -z "${ys}" ]; then yamllint "${ys}"; else true; fi'

shellcheck:
  stage: lint
  script:
    - shellcheck $(find -path */.terraform/* -prune
                     -o -name '*.sh'
                     -print)

ubuntu-xenial-ami:
  stage: build
  script:
    - cd ./ubuntu-xenial
    - make build
  artifacts:
    paths:
      - "${CI_JOB_NAME}.txt"
      - "${CI_JOB_NAME}-manifest.json"
  variables:
    CI_JOB_NAME: 'ubuntu-xenial-ami'
