---
image: registry.dev-sandbox.fpcomplete.com/ops/default-build-image@sha256:ec289ae8a83e25afd594b64fb5ca098eeedbb7a7b0983d5396b645841164996b

stages:
  - lint

yamllint:
  stage: lint
  script:
    - yamllint $(find -path */.terraform/*
                   -o -path ./.gitlab-ci.yml
                   -prune
                   -o -iname '*.yaml'
                   -o -iname '*.yml'
                   -print)

shellcheck:
  stage: lint
  script:
    - shellcheck $(find -path */.terraform/* -prune
                     -o -name '*.sh'
                     -print)
